version: "2"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    # - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/volodya-nrg/tools)
        - blank
      custom-order: true
linters:
  default: none
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    #    - cyclop
    - decorder
    #    - depguard
    - dogsled
    #    - dupl
    #    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    #    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    #    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    #    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    #    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    #    - gocognit
    - goconst
    - gocritic
    #    - gocyclo
    #    - godot
    #    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    #    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    #    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    #    - nlreturn
    - noctx
    #    - noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    #    - tagalign
    #    - tagliatelle
    - testableexamples
    - testifylint
    #    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    #    - wrapcheck
    #    - wsl
    #    - wsl_v5
    - zerologlint
  settings:
    importas:
      alias:
        - pkg: crypto/rand
          alias: cryptorand
    staticcheck:
      # Default: ["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "SIP", "RTP", "AMQP", "DB", "TS"]
      initialisms: [ "ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "SIP", "RTP", "AMQP", "DB", "TS" ]
    errorlint:
      errorf: false
    varnamelen:
      min-name-length: 1
    revive:
      rules:
        - name: var-naming
          disabled: true
    gosec:
      excludes:
        - G204
        - G115
        - G304
    funcorder:
      constructor: false
      struct-method: false
    mnd:
      checks:
        - case
        - condition
        - return
        - assign
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - intrange
          - maintidx
